### ISSUE TITLE
list buffer_radius argument consistently across images

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/aadt#2]
To change a default buffer radius, a user can optionally supply an additional argument to a DeGAUSS container.

`roads` is suggested to be run as `docker run --rm -v "$PWD":/tmp degauss/roads:0.1 my_address_file_geocoded.csv --buffer_radius 500`

But, `aadt` suggested to be run as `docker run --rm -v $PWD:/tmp /degauss/aadt:0.1.1 my_address_file_geocoded.csv 500`

I think we should add `--buffer_radius` here too, but wanted to make sure that the actual argument wasn't called something else.  These should both work, right?  Just being consistent for documentation's sake...

**Comment by erikarasnick** [comment]
I went to check this out and realized I can't even pull the aadt container from ghcr. I went to check out the package settings, but I don't have the button for it.

Do you see it [here](https://github.com/degauss-org/aadt/pkgs/container/aadt)? It should be the last thing on the right panel. I have it for the other packages, so I'm guessing there is something going on with my permissions? 

I also just noticed an extra `/` in the docker call for aadt, which probably came from using the template.

**Comment by erikarasnick** [comment]
maybe it's not permissions because I can't pull the pm container either... 

This is my error 
`
docker: Error response from daemon: Head https://ghcr.io/v2/degauss-org/aadt/manifests/0.1.1: denied: denied.
`

**Comment by cole-brokamp** [comment]
I can pull aadt okay.

**Comment by erikarasnick** [comment]
I am still trying to figure out why I can't pull containers from ghcr. 

But I looked in the [code](https://github.com/degauss-org/aadt/blob/abc1a964664ad66fc90385eb9aa413bfa091743f/entrypoint.R#L11) and the argument is called `buffer_radius` but we use {docopt} for aadt and {argparser} for roads. 

Since I can't pull from ghcr, I used v 0.1.0 from docker hub and `docker run --rm -v $PWD:/tmp /degauss/aadt:0.1.0 my_address_file_geocoded.csv --buffer_radius 500` does not work. This is the error 

```
Error: 
      Usage:
      entrypoint.R <filename> [<buffer_radius>]
      
Execution halted
```

I'm not sure why, but even though the argument is named `buffer_radius` the {docopt} syntax doesn't like it specified that way.

**Comment by cole-brokamp** [comment]
OK, the [dht template](https://github.com/degauss-org/dht/blob/a6c88bed4c2bce04109a555487feec92000dc4d2/inst/degauss_entrypoint.R#L14) uses {docopt}, so let's stick with that.
